### ISSUE TITLE
Speed up test suite

### ISSUE THREAD

**Issue by fredrikaverpil** [fredrikaverpil/creosote#143]
### What feature request would you like to suggest?

Instead of actually calling `pip` or `poetry`, I'd like to get rid of these slow tests and instead mock and use fast unit testing. Some refactoring is being made in #142 which will make it easier to mock the dependency file reader. Pytest fixtures should be made for adding dependencies, excluding dependencies, returning a deps/venv/distlib/canonicalization resolve etc.

- [ ] Add enough fixtures and tests around defining packages/venv etc so that the slow integration tests can be replaced with faster and equally reliable tests.
- [ ] Would also be nice to add a coverage report, so to easily spot uncovered logic.
- [x] Would like to remove poetry as a required dependency for running the test suite.
- [x] Use built in caching from actions/setup-python:

```yml
- uses: actions/setup-python@v4
  with:
    cache: 'pip'
    cache-dependency-path: 'pyproject.toml'
```

### Will the feature request break backwards compatibility?

No.
